[package]
name = "ethereum-tx-sign"
version = "0.0.1"
description = ""
homepage = ""
repository = ""
documentation = ""
license = "MIT"
keywords = ["web3", "ethereum", "transaction", "sign"]
authors = ["Mate Antunovic <mateATantunovic.nz>"]
readme = "README.md"

[dependencies]
ethereum-types = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak="1.4.2"
secp256k1 = "0.11.1"
rlp = "0.2.2"
